language: python

os:
  - linux
env:
  - CUDA=8.0.61-1

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

#before_install:
#  -  source script/travis/install_cuda.sh

install:
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../cuda_functions -m unittest discover . "*_test.py"

after_success:
    - coveralls
    - cd ../..