language: python
dist: trusty
sudo: required

os:
  - linux

env:
  - CUDA=7.0-28
  - CUDA=7.5-18
  - CUDA=8.0.61-1

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development

before_install:
  -  export CUDA_INSTALL_EXTRA_LIBS=0
  -  source travis/install-cuda.sh

install:
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd unittest
    - coverage run --source=../cuda_functions -m unittest discover . "dummy.py"

after_success:
    - coveralls
    - cd ../..